---
title: "DSM Straying Model Documentation"
output: 
  html_document:
    theme: flatly
    code_folding: hide
vignette: >
  %\VignetteIndexEntry{temperature-model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Chinook supplementary analysis for Chinook DSM models

### Empirical model to describe adult straying 


#### Data Source: 

This analysis is done using 2008–2011 tagging data provided by East Bay Municipal Utility District. The data can be accessed from the following links:

* [cwt_stray.csv](https://dsm-docs.s3-us-west-2.amazonaws.com/straying-data/cwt_stray.csv)
* [releases.csv](https://dsm-docs.s3-us-west-2.amazonaws.com/straying-data/releases.csv)
* [crxchan.csv](https://dsm-docs.s3-us-west-2.amazonaws.com/straying-data/crxchan.csv)


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(readr)
library(tidyverse)
library(DT)
```

```{r}
library(fallRunDSM)
cwt_stray = read_csv(system.file("extdata", "straying-data", "cwt_stray.csv", 
                       package = "fallRunDSM", mustWork = TRUE))

releases = read_csv(system.file("extdata", "straying-data", "releases.csv", 
                       package = "fallRunDSM", mustWork = TRUE))

dat = read_csv(system.file("extdata", "straying-data", "crxchan.csv", 
                       package = "fallRunDSM", mustWork = TRUE)) %>% 
  rename("run_year" = Run.year,
         "count" = Number,
         "prop_stray" = prop.stray,
         "pulse" = Pulsed,
         "closure_days" = Closure.days,
         "prop_sacramento" = Prp.sac,
         "prop_san_joaquin" = Prp.sj)
```
Prep data create a dataframe:
```{r}
releases <- releases[-2,]
combined_stray_data <- merge(cwt_stray, releases, all = T)

fall <- combined_stray_data %>% 
  filter(run == "Fall") %>%
  mutate(no_tagged = ifelse(is.na(`no tagged`), 
                            no.woth.CTW, `no tagged`),
         prop_stray = ifelse(is.na(prop.stray), 0, prop.stray),
         no_stray = round(no_tagged * prop_stray),
         brood_year = as.factor(Brood.yr)) %>%
  select(no_tagged, prop_stray, no_stray, 
         brood_year, "wild" = Wild, 
         "delta" = Delta, "bay" = Bay)

datatable(fall,
          options = list(
                    searching = FALSE,
                    pageLength = 5,
                    lengthMenu = c(5, 10, 15, 20)
))
```

```{r}
outz <- glm(cbind(no_stray, no_tagged) ~ brood_year + delta + bay + wild, family = quasibinomial, data = fall)

summary(outz)
# plot(outz)
```

Cross channel analysis 
```{r}
names(dat)

dat$no_stray <- round(dat$count * dat$prop_stray)

outz <- glm(cbind(no_stray, count) ~ closure_days + prop_san_joaquin, family = binomial, data = dat)

summary(outz)
```

